name: Docker Image Build
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: europe-west3-docker.pkg.dev/finveloxrepos/image-repo
  IMAGE_NAME: pergamon

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get tag
      id: get-tag
      run: echo "full_tag=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(gradle properties | grep 'version:' | cut -d ' ' -f 2)" >> "$GITHUB_OUTPUT"
    - id: auth
      name: Google Cloud Authentication
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'finveloxrepos'
        token_format: access_token
        service_account: artifactory-service-account@finveloxrepos.iam.gserviceaccount.com
        workload_identity_provider: 'projects/36190201445/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider'
    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Build the Docker image
      run: echo "docker build . --file dockerfile-native --tag ${{ steps.get-tag.outputs.full_tag }}"
    - name: Push the Docker image
      run: echo "docker image push ${{ steps.get-tag.outputs.full_tag }}"
