name: Docker Image Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: List files
      run: |
        ls -l ${{ github.workspace }}
    - name: Build the Docker image
      run: docker build . --file dockerfile-native --tag pergamon:$(gradle properties | grep 'version:' | cut -d ' ' -f 2)
