name: Docker Image Build
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: europe-west3-docker.pkg.dev/mavendeneme/docker-private
  IMAGE_NAME: pergamon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: List files
      run: |
        ls -l ${{ github.workspace }}
    - name: Get tag
      id: get-tag
      run: echo ::set-output name=full_tag::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(gradle properties | grep 'version:' | cut -d ' ' -f 2)
    - name: Build the Docker image
      run: docker build . --file dockerfile-native --tag ${{ steps.get-tag.outputs.full_tag }}
    - id: auth
      name: Google Cloud Authentication
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'mavendeneme'
        workload_identity_provider: 'projects/822842382134/locations/global/workloadIdentityPools/github-pool/providers/github-actions-pr'
    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Push the Docker image
      run: docker image push --tag ${{ steps.get-tag.outputs.full_tag }}
